### ISSUE TITLE
guiscrcpy ~ mapper is not initialized

### ISSUE THREAD

**Issue by hendikawp** [srevinsaju/guiscrcpy#85]
```
guiscrcpy ~ mapper is not initialized. Initialize by running
$ guiscrcpy-mapper 

reset points by
$ guiscrcpy-mapper -r
```

when i write this command to terminal : guiscrcpy-mapper -r

i got this 
```
+++++++++++++++++++++++++++++++++++++++
guiscrcpy ~ mapper by srevinsaju
=======================================
Make sure that your device is turned on, and connected to your PC
With USB debugging turned on.
+++++++++++++++++++++++++++++++++++++++
Waiting for device
Device : OK!
Traceback (most recent call last):
  File "/usr/local/bin/guiscrcpy-mapper", line 22, in <module>
    os.remove(cfgpath+"guiscrcpy.mapper.json")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu-budgie/.config/guiscrcpy/guiscrcpy.mapper.json'
```
how to fix??

**Comment by srevinsaju** [comment]
Remove everything in `~/.config/guiscrcpy/*` and then,
If `~/.config/guiscrcpy/` doesn't exist, create that folder

* connect your device
* run guiscrcpy
* check if you can start your device and view your screen
* close guiscrcpy
* Keep your mobile on, and go to the app you would like to map the points, 
* run `guiscrcpy-mapper`
* you should now see a window with your phone's screenshot
* follow the onscreen instructions 
* close the window, your config will be saved 
* Now run `guiscrcpy-mapper` again to start the mapping daemon.
* Now, when you press any key, that mapped tap will be done

**Comment by hendikawp** [comment]
i got this 

LOG: Detected a Linux Operating System ::  5.4.0-21-generic #25-Ubuntu SMP Sat Mar 28 13:10:28 UTC 2020
[  6%] /sdcard/scr.png
[ 13%] /sdcard/scr.png
[ 20%] /sdcard/scr.png
[ 26%] /sdcard/scr.png
[ 33%] /sdcard/scr.png
[ 40%] /sdcard/scr.png
[ 46%] /sdcard/scr.png
[ 53%] /sdcard/scr.png
[ 60%] /sdcard/scr.png
[ 67%] /sdcard/scr.png
[ 73%] /sdcard/scr.png
[ 80%] /sdcard/scr.png
[ 87%] /sdcard/scr.png
[ 93%] /sdcard/scr.png
[100%] /sdcard/scr.png
/sdcard/scr.png: 1 file pulled. 25.8 MB/s (976338 bytes in 0.036s)


libpng error: Read Error
Lets Check

**Comment by srevinsaju** [comment]
Thanks @hendikawp . Looks interesting. Which OS are you using?

**Comment by hendikawp** [comment]
+++++++++++++++++++++++++++++++++++++++
guiscrcpy ~ mapper by srevinsaju
=======================================
Make sure that your device is turned on, and connected to your PC
With USB debugging turned on.
+++++++++++++++++++++++++++++++++++++++
Waiting for device
Device : OK!
LOG: Initializing guiscrcpy.mapper() for first time use...
LOG: Key:Pos JSON Configuration file created in  /home/decka/.config/guiscrcpy/  directory
LOG: Detected a Linux Operating System ::  5.4.0-21-generic #25-Ubuntu SMP Sat Mar 28 13:10:28 UTC 2020
[  5%] /sdcard/scr.png
[ 11%] /sdcard/scr.png
[ 17%] /sdcard/scr.png
[ 22%] /sdcard/scr.png
[ 28%] /sdcard/scr.png
[ 34%] /sdcard/scr.png
[ 40%] /sdcard/scr.png
[ 45%] /sdcard/scr.png
[ 51%] /sdcard/scr.png
[ 57%] /sdcard/scr.png
[ 63%] /sdcard/scr.png
[ 68%] /sdcard/scr.png
[ 74%] /sdcard/scr.png
[ 80%] /sdcard/scr.png
[ 86%] /sdcard/scr.png
[ 91%] /sdcard/scr.png
[ 97%] /sdcard/scr.png
[100%] /sdcard/scr.png
/sdcard/scr.png: 1 file pulled. 25.9 MB/s (1140418 bytes in 0.042s)


libpng error: Read Error
Lets Check

**Comment by hendikawp** [comment]
![scr](https://user-images.githubusercontent.com/63694567/79331201-06191700-7f45-11ea-949c-f94ac9a62226.png)
screenshoot is corrupted

**Comment by srevinsaju** [comment]
Thanks.

I suppose, you should try it again after removing the files. The screenshot taken by the device can be corrupted at times when using a graphic intensive game.

In case, re initializing `guiscrcpy-mapper` doesn't work, then , try taking a screenshot on your mobile of the PubG game, and then open it in your mobile gallery. Then run `guiscrcpy-mapper` after deleting the files. It should work now ;)

**Comment by hendikawp** [comment]
i try again with open config button in pubg, guiscrcpy-mapper succes, i dont know why

how to map right clight n left click?

**Comment by hendikawp** [comment]
![scr](https://user-images.githubusercontent.com/63694567/79334264-2697a000-7f4a-11ea-984b-1ac9e8958c96.png)

but still cannot map my key Lol
this app very recomended, no lag

**Comment by srevinsaju** [comment]
I apologize. `guiscrcpy` only supports keyboard mapping, i.e, making use of letters only. I still didn't learn how to handle mouse button actions. Hope you enjoy guiscrcpy

**Comment by hendikawp** [comment]
thanks for your attention
thanks for your support
